version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  postgres:
    image: postgres:11.6
  
  django: &django
    build:
      context: ./
      dockerfile: ./compose/local/django/Dockerfile
    image: api-story-architect
    depends_on:
      - postgres
    volumes:
      - ./src:/app
    working_dir: /app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.db
      - ./.envs/.local/.cloud
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    command: /start
#
#  redis:
#    image: redis:6.2
#