# Generated by Django 3.2 on 2025-12-04 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('last_commit_hash', models.CharField(blank=True, max_length=40)),
                ('last_commit_message', models.TextField(blank=True)),
                ('last_commit_author', models.CharField(blank=True, max_length=200)),
                ('last_commit_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Git branches',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TerraformModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=500)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('path', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_modules', to='terraform.terraformmodule')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TerraformProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('git_repository_url', models.URLField(blank=True, null=True)),
                ('git_branch', models.CharField(default='main', max_length=200)),
                ('git_commit_hash', models.CharField(blank=True, max_length=40)),
                ('terraform_version', models.CharField(default='1.6.0', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terraform_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TerraformProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='terraform.terraformproject')),
            ],
            options={
                'ordering': ['name', 'alias'],
            },
        ),
        migrations.CreateModel(
            name='TerraformStateFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('terraform_version', models.CharField(max_length=20)),
                ('serial', models.IntegerField()),
                ('lineage', models.CharField(max_length=100)),
                ('state_data', models.JSONField()),
                ('resources_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_files', to='terraform.gitbranch')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_files', to='terraform.terraformproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerraformResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(db_index=True, max_length=200)),
                ('resource_name', models.CharField(db_index=True, max_length=200)),
                ('terraform_address', models.CharField(max_length=500, unique=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('planning', 'Planning'), ('applying', 'Applying'), ('created', 'Created'), ('updating', 'Updating'), ('error', 'Error'), ('destroyed', 'Destroyed')], default='unknown', max_length=20)),
                ('state_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='terraform.terraformmodule')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='terraform.terraformproject')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='terraform.terraformprovider')),
            ],
            options={
                'ordering': ['resource_type', 'resource_name'],
            },
        ),
        migrations.CreateModel(
            name='TerraformOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('sensitive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='terraform.terraformmodule')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='terraform.terraformproject')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='terraformmodule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='terraform.terraformproject'),
        ),
        migrations.CreateModel(
            name='TerraformExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_type', models.CharField(choices=[('init', 'Init'), ('plan', 'Plan'), ('apply', 'Apply'), ('destroy', 'Destroy'), ('refresh', 'Refresh')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('plan_output', models.TextField(blank=True)),
                ('changes_summary', models.JSONField(blank=True, null=True)),
                ('logs', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='terraform.gitbranch')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terraform_executions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='terraform.terraformproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dependency_type', models.CharField(choices=[('implicit', 'Implicit'), ('explicit', 'Explicit'), ('data', 'Data')], default='implicit', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_from', to='terraform.terraformresource')),
                ('to_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_to', to='terraform.terraformresource')),
            ],
            options={
                'verbose_name_plural': 'Resource dependencies',
            },
        ),
        migrations.CreateModel(
            name='ResourceCloudStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cloud_resource_id', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('cost_per_hour', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_checked_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_status', to='terraform.terraformresource')),
            ],
            options={
                'verbose_name_plural': 'Resource cloud statuses',
                'ordering': ['-last_checked_at'],
            },
        ),
        migrations.AddField(
            model_name='gitbranch',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_branches', to='terraform.terraformproject'),
        ),
        migrations.CreateModel(
            name='TerraformVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('sensitive', models.BooleanField(default=False)),
                ('validation_rules', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='terraform.terraformmodule')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='terraform.terraformproject')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'module', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='terraformstatefile',
            index=models.Index(fields=['project', 'version'], name='terraform_t_project_f1d2b8_idx'),
        ),
        migrations.AddIndex(
            model_name='terraformstatefile',
            index=models.Index(fields=['created_at'], name='terraform_t_created_6a527f_idx'),
        ),
        migrations.AddIndex(
            model_name='terraformresource',
            index=models.Index(fields=['project', 'resource_type'], name='terraform_t_project_bc9408_idx'),
        ),
        migrations.AddIndex(
            model_name='terraformresource',
            index=models.Index(fields=['terraform_address'], name='terraform_t_terrafo_868cb4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='terraformprovider',
            unique_together={('project', 'name', 'alias')},
        ),
        migrations.AddIndex(
            model_name='terraformproject',
            index=models.Index(fields=['user', 'name'], name='terraform_t_user_id_963409_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='terraformoutput',
            unique_together={('project', 'module', 'name')},
        ),
        migrations.AddIndex(
            model_name='terraformexecution',
            index=models.Index(fields=['project', 'status'], name='terraform_t_project_7dde10_idx'),
        ),
        migrations.AddIndex(
            model_name='terraformexecution',
            index=models.Index(fields=['created_at'], name='terraform_t_created_2e92dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcedependency',
            unique_together={('from_resource', 'to_resource')},
        ),
        migrations.AddIndex(
            model_name='resourcecloudstatus',
            index=models.Index(fields=['last_checked_at'], name='terraform_r_last_ch_64ccbc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gitbranch',
            unique_together={('project', 'name')},
        ),
    ]
