# Generated by Django 3.2 on 2025-12-04 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terraform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudProviderCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('provider_type', models.CharField(choices=[('aws', 'Amazon Web Services'), ('azure', 'Microsoft Azure'), ('gcp', 'Google Cloud Platform'), ('digitalocean', 'DigitalOcean'), ('other', 'Other')], max_length=50)),
                ('_aws_access_key_id', models.TextField(blank=True, db_column='aws_access_key_id')),
                ('_aws_secret_access_key', models.TextField(blank=True, db_column='aws_secret_access_key')),
                ('_aws_session_token', models.TextField(blank=True, db_column='aws_session_token')),
                ('aws_region', models.CharField(blank=True, max_length=50)),
                ('_azure_subscription_id', models.TextField(blank=True, db_column='azure_subscription_id')),
                ('_azure_tenant_id', models.TextField(blank=True, db_column='azure_tenant_id')),
                ('_azure_client_id', models.TextField(blank=True, db_column='azure_client_id')),
                ('_azure_client_secret', models.TextField(blank=True, db_column='azure_client_secret')),
                ('_gcp_project_id', models.TextField(blank=True, db_column='gcp_project_id')),
                ('_gcp_service_account_json', models.TextField(blank=True, db_column='gcp_service_account_json')),
                ('_generic_credentials', models.TextField(blank=True, db_column='generic_credentials')),
                ('is_default', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='terraformprovider',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='terraform.cloudprovidercredential'),
        ),
        migrations.AddIndex(
            model_name='cloudprovidercredential',
            index=models.Index(fields=['user', 'provider_type'], name='terraform_c_user_id_bf0734_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cloudprovidercredential',
            unique_together={('user', 'name')},
        ),
    ]
