# Generated by Django 3.2 on 2025-12-04 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terraform', '0002_auto_20251204_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformresource',
            name='availability_zone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='terraformresource',
            name='parent_resource',
            field=models.ForeignKey(blank=True, help_text='Parent container resource (e.g., subnet for an instance)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contained_resources', to='terraform.terraformresource'),
        ),
        migrations.AddIndex(
            model_name='terraformresource',
            index=models.Index(fields=['parent_resource'], name='terraform_t_parent__a0a83a_idx'),
        ),
    ]
