# Generated by Django 3.2 on 2025-12-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraform', '0003_auto_20251204_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformresource',
            name='is_data_source',
            field=models.BooleanField(default=False, help_text='True if this is a data source (queries existing infrastructure), False if managed resource'),
        ),
    ]
