# Generated by Django 3.2 on 2022-08-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='content',
            name='name_es',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
