# Generated by Django 3.2 on 2022-08-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20220812_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='content',
            name='name_es',
        ),
    ]
