# Generated by Django 3.2 on 2022-08-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20220812_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_es',
        ),
        migrations.AddField(
            model_name='content',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='content/% Y/% m/% d/'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_number',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content_text_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('T', 'Text'), ('N', 'Number'), ('I', 'Image')], default='T', max_length=5),
        ),
    ]
