# Generated by Django 3.2 on 2022-08-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20220830_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='content/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('T', 'Text'), ('N', 'Number'), ('I', 'Image'), ('J', 'Json')], default='T', max_length=5),
        ),
    ]
