# Generated by Django 3.2 on 2022-09-30 03:09

import api.cms.models.contents
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20220830_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            bases=(api.cms.models.contents.ContentModel, models.Model),
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('content', models.ImageField(blank=True, null=True, upload_to='content/%Y/%m/%d/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.contentgroup')),
            ],
            bases=(api.cms.models.contents.ContentModel, models.Model),
        ),
        migrations.CreateModel(
            name='ContentNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('content', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='cms.contentgroup')),
            ],
            bases=(api.cms.models.contents.ContentModel, models.Model),
        ),
        migrations.CreateModel(
            name='ContentObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('content', models.JSONField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='cms.contentgroup')),
            ],
            bases=(api.cms.models.contents.ContentModel, models.Model),
        ),
        migrations.CreateModel(
            name='ContentText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_es', models.TextField(blank=True, null=True)),
                ('content_en', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='cms.contentgroup')),
            ],
            bases=(api.cms.models.contents.ContentModel, models.Model),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
