# Generated by Django 3.2 on 2022-09-30 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20220930_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentimage',
            old_name='content',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='contentnumber',
            old_name='content',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='contentobject',
            old_name='content',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='contenttext',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contenttext',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='contenttext',
            name='content_es',
        ),
        migrations.AddField(
            model_name='contenttext',
            name='value',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='contenttext',
            name='value_en',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='contenttext',
            name='value_es',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='contentobject',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objs', to='cms.contentgroup'),
        ),
    ]
