# Generated by Django 3.2 on 2023-01-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20220930_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimage',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='contentnumber',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='contentobject',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='contenttext',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
