# Generated by Django 3.2 on 2023-01-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20230110_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttext',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenttext',
            name='value_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenttext',
            name='value_es',
            field=models.TextField(blank=True, null=True),
        ),
    ]
