# Generated by Django 3.2 on 2023-02-17 01:18

import api.cms.models.contents
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20230125_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentimage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.contentgroup'),
        ),
        migrations.CreateModel(
            name='ContentProjectBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_benefits', to='cms.contentgroup')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_benefits', to='cms.contentimage')),
            ],
            bases=(api.cms.models.contents.ContentModel, models.Model),
        ),
        migrations.CreateModel(
            name='ContentPlatformBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_benefits', to='cms.contentgroup')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_benefits', to='cms.contentimage')),
            ],
            bases=(api.cms.models.contents.ContentModel, models.Model),
        ),
        migrations.CreateModel(
            name='ContentInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('opinion', models.CharField(blank=True, max_length=512, null=True)),
                ('investor_name', models.CharField(blank=True, max_length=512, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='cms.contentgroup')),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors', to='cms.contentimage')),
            ],
            bases=(api.cms.models.contents.ContentModel, models.Model),
        ),
    ]
