# Generated by Django 3.2 on 2023-02-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20230125_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnumber',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
