# Generated by Django 3.2 on 2023-02-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20230217_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentinvestor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='content/investors/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='contentplatformbenefit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/platform-benefits/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='contentprojectbenefit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/project-benefits/%Y/%m/%d/'),
        ),
    ]
