# Generated by Django 3.2 on 2023-02-17 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_contentnumber_value'),
        ('cms', '0011_auto_20230217_0123'),
    ]

    operations = [
    ]
