# Generated by Django 3.2 on 2023-02-20 18:26

import api.cms.models.contents
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_merge_20230217_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFrequentlyAskedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='content/questions/%Y/%m/%d/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cms.contentgroup')),
            ],
            bases=(api.cms.models.contents.ContentModel, models.Model),
        ),
    ]
