# Generated by Django 3.2 on 2023-02-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_contentfrequentlyaskedquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentfrequentlyaskedquestion',
            name='group',
        ),
        migrations.AddField(
            model_name='contentfrequentlyaskedquestion',
            name='groups',
            field=models.ManyToManyField(related_name='questions', to='cms.ContentGroup'),
        ),
    ]
