# Generated by Django 3.2 on 2023-02-22 17:46

import api.cms.models.contents
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20230222_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('social_media_name', models.CharField(blank=True, max_length=512, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='content/social-media/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('account_name', models.CharField(blank=True, max_length=512, null=True)),
                ('groups', models.ManyToManyField(related_name='social_media_account', to='cms.ContentGroup')),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_account', to='cms.socialmedia')),
            ],
            bases=(api.cms.models.contents.ContentModel, models.Model),
        ),
        migrations.CreateModel(
            name='PlatformUserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('opinion', models.CharField(blank=True, max_length=512, null=True)),
                ('user_name', models.CharField(blank=True, max_length=512, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='content/platform-users/%Y/%m/%d/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_user_reviews', to='cms.contentgroup')),
            ],
            bases=(api.cms.models.contents.ContentModel, models.Model),
        ),
        migrations.CreateModel(
            name='FooterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('text', models.CharField(blank=True, max_length=512, null=True)),
                ('redirection', models.CharField(blank=True, max_length=512, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_item', to='cms.contentgroup')),
            ],
            bases=(api.cms.models.contents.ContentModel, models.Model),
        ),
    ]
