# Generated by Django 3.2 on 2023-02-24 14:38

import api.cms.models.contents
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_footeritem_platformuserreview_socialmedia_socialmediaaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            bases=(api.cms.models.contents.ContentModel, models.Model),
        ),
        migrations.AddField(
            model_name='footeritem',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_item', to='cms.footersection'),
        ),
    ]
