# Generated by Django 3.2 on 2023-02-24 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20230224_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footeritem',
            name='group',
        ),
        migrations.RemoveField(
            model_name='footeritem',
            name='name',
        ),
        migrations.AddField(
            model_name='footersection',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_sections', to='cms.contentgroup'),
        ),
        migrations.AddField(
            model_name='footersection',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='footeritem',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_items', to='cms.footersection'),
        ),
    ]
