# Generated by Django 3.2 on 2023-04-18 15:37

import api.cms.models.contents
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_alter_contentlittlerobinlevels_target_amount_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPaymentsMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('text', models.CharField(blank=True, max_length=512, null=True)),
                ('type', models.CharField(blank=True, choices=[('BK', 'BANK'), ('PM', 'PALOMMA'), ('WP', 'WOMPI')], max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=512, null=True)),
                ('account_name', models.CharField(blank=True, max_length=512, null=True)),
                ('nit', models.CharField(blank=True, max_length=512, null=True)),
                ('account_type', models.CharField(blank=True, max_length=512, null=True)),
                ('account_number', models.CharField(blank=True, max_length=512, null=True)),
                ('qr', models.ImageField(blank=True, null=True, upload_to='content/payments_methods_qr/%Y/%m/%d/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='content/payments_methods/%Y/%m/%d/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_methods', to='cms.contentgroup')),
            ],
            bases=(api.cms.models.contents.ContentModel, models.Model),
        ),
    ]
