# Generated by Django 3.2 on 2023-04-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_alter_contentlittlerobinlevels_target_amount_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfrequentlyaskedquestion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentfrequentlyaskedquestion',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
