# Generated by Django 3.2 on 2023-04-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_auto_20230419_1111'),
        ('cms', '0022_contentrecommendationoptions'),
    ]

    operations = [
    ]
