# Generated by Django 3.2 on 2023-05-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_merge_20230429_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpaymentsmethods',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
