# Generated by Django 3.2 on 2023-05-17 14:49

import api.cms.models.contents
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_contentpaymentsmethods_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value', models.FileField(blank=True, null=True, upload_to='content/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cms.contentgroup')),
            ],
            bases=(api.cms.models.contents.ContentModel, models.Model),
        ),
    ]
